In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy.stats import norm
import scipy.stats as stats
import math
from datetime import datetime

In [5]:
pnl_df = pd.read_csv('/Users/zhengyaojin/Desktop/Bluestar_PnL.csv')

In [6]:
pnl_clean = pnl_df.drop(columns=['category', 'feed', 'file', 'client', 'subset',
                                 'august_2024', 'september_2024', 'october_2024', 'november_2024',
                                 'december_2024', 'january_2025', 'february_2025',
                                 'march_2025', 'april_2025', 'may_2025', 'june_2025'])

In [7]:
# Separate the df into four based on 'account_type'
sales_df = pnl_clean[pnl_clean['account_type'] == 'Sales']
direct_costs_df = pnl_clean[pnl_clean['account_type'] == 'Direct Costs']
other_income_df = pnl_clean[pnl_clean['account_type'] == 'Other Income']
expense_df = pnl_clean[pnl_clean['account_type'] == 'Expense']

sales_df_sorted = sales_df.sort_values(by='account')
direct_costs_df_sorted = direct_costs_df.sort_values(by='account')
other_income_df_sorted = other_income_df.sort_values(by='account')
expense_df_sorted = expense_df.sort_values(by='account')

In [5]:
# # # sales_df
# columns_to_sum_sales = sales_df.columns[3:]
# column_sums_sales = sales_df[columns_to_sum_sales].sum()
# print(column_sums_sales)

In [38]:
# expense_df
# columns_to_sum_ex = expense_df.columns[3:]
# column_sums_ex = expense_df[columns_to_sum_ex].sum()
# print(column_sums_ex)

june_2023        -6.824201e+05
july_2023        -1.866905e+06
august_2023      -2.023235e+06
september_2023   -2.042758e+06
october_2023     -2.040512e+06
november_2023    -2.059237e+06
december_2023    -2.082069e+06
january_2024     -2.131580e+06
february_2024    -2.057131e+06
march_2024       -2.296994e+06
april_2024       -2.058850e+06
may_2024         -2.111974e+06
june_2024        -2.095025e+06
july_2024        -3.899406e+06
dtype: float64

In [7]:
# # create a dict to store EBITDA percentage of revenue
# months_dict = {
#     'january': '',
#     'february': '',
#     'march': '',
#     'april': '',
#     'may': '',
#     'june': '',
#     'july': '',
#     'august': '',
#     'september': '',
#     'october': '',
#     'november': '',
#     'december': ''
# }

In [9]:
# Define the columns to sum up
columns_to_sum = ['june_2023', 'july_2023', 'august_2023', 'september_2023',
                  'october_2023', 'november_2023', 'december_2023',
                  'january_2024', 'february_2024', 'march_2024', 'april_2024',
                  'may_2024', 'june_2024', 'july_2024']

column_sums = sales_df_sorted[columns_to_sum].fillna(0).sum()

print(column_sums)

june_2023         2.333799e+06
july_2023         7.620739e+06
august_2023       8.639362e+06
september_2023    8.230057e+06
october_2023      9.583309e+06
november_2023     9.652704e+06
december_2023     8.144510e+06
january_2024      8.203145e+06
february_2024     8.380625e+06
march_2024        8.292806e+06
april_2024        8.639735e+06
may_2024          9.278841e+06
june_2024         8.059366e+06
july_2024         1.509162e+07
dtype: float64

In [10]:
# Calculate the percentage for sales, direct costs, other income, and expense df
sales_df_sorted[columns_to_sum] = sales_df_sorted[columns_to_sum].div(column_sums, axis=1)
direct_costs_df_sorted[columns_to_sum] = direct_costs_df_sorted[columns_to_sum].div(column_sums, axis=1)
other_income_df_sorted[columns_to_sum] = other_income_df_sorted[columns_to_sum].div(column_sums, axis=1)
expense_df_sorted[columns_to_sum] = expense_df_sorted[columns_to_sum].div(column_sums, axis=1)

In [11]:
expense_df_sorted

,account_type,account_code,account,june_2023,july_2023,august_2023,september_2023,october_2023,november_2023,december_2023,january_2024,february_2024,march_2024,april_2024,may_2024,june_2024,july_2024
80,Expense,64010.0,Accounting Fees Expense,-0.009680,-0.001327,-1.360054e-03,-2.065599e-03,-0.001458,-1.077418e-03,-1.838969e-03,-2.900107e-03,-1.239466e-03,NaN,-0.001716,-3.394821e-04,-0.001251,-0.000822
75,Expense,63100.0,Advertising,NaN,-0.000525,-1.041744e-03,-1.161900e-03,-0.000949,-9.323812e-04,-1.217044e-03,-3.505152e-03,-4.690274e-03,-5.167777e-03,-0.002975,-2.915807e-03,-0.004686,-0.004148
79,Expense,63510.0,Amortisation (63510),-0.000161,-0.000213,-1.446866e-04,-1.518823e-04,-0.000130,-1.294974e-04,-1.534776e-04,-1.523806e-04,-1.491536e-04,-1.507331e-04,-0.000145,-1.347151e-04,-0.000155,NaN
89,Expense,64184.0,Asset <$300 or 2yr Eff Life,NaN,-0.000275,-4.677429e-04,-3.444116e-03,NaN,NaN,-2.400856e-04,-1.432889e-04,NaN,NaN,NaN,NaN,NaN,NaN
81,Expense,64011.0,Audit Fees,NaN,NaN,NaN,-2.794634e-03,-0.004299,NaN,-1.271987e-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Expense,64140.0,Bad debts,NaN,NaN,NaN,NaN,-0.000129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
84,Expense,64130.0,Bank Charges,NaN,-0.000072,-5.666044e-05,-9.111237e-05,-0.000010,-2.744930e-05,-1.111178e-05,-1.053864e-04,-1.095348e-04,-2.641446e-05,-0.000054,-4.849744e-06,-0.000004,-0.002350
95,Expense,497.0,Bank Revaluations,NaN,NaN,NaN,1.668657e-03,NaN,NaN,-6.591753e-04,NaN,4.623641e-04,-6.772376e-05,0.000085,-1.566898e-04,0.000032,-0.000008
85,Expense,64132.0,Bank account fees,-0.006419,-0.002409,-2.124855e-03,-2.293774e-03,-0.001963,-1.954161e-03,-3.314751e-03,-3.438484e-03,-3.325687e-03,-3.266283e-03,-0.003103,-2.994156e-03,-0.003102,-0.000264
86,Expense,64138.0,Bank merchant fees,NaN,-0.000202,-1.863193e-04,-1.855734e-04,-0.000173,-3.036662e-05,-3.354529e-05,-1.175878e-04,-1.133639e-04,-3.080622e-05,-0.000264,-9.877850e-05,-0.000103,-0.000056
69,Expense,64740.0,Car Allowances - HO,-0.000082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Expense,64652.0,Cleaning,-0.005088,-0.002125,-2.171449e-03,-4.647557e-03,-0.002382,-2.721341e-03,-2.821773e-03,-2.690568e-03,-2.717895e-03,-2.373607e-03,-0.003254,-2.445811e-03,-0.003052,-0.001867
71,Expense,64160.0,Collection costs,-0.000308,-0.000096,-8.325499e-05,-8.739550e-05,-0.000124,-7.451487e-05,-8.831347e-05,-8.768222e-05,-8.582534e-05,-8.673421e-05,-0.000083,-7.751722e-05,-0.000096,NaN
91,Expense,64210.0,Director's Fees,-0.004285,-0.004891,-4.721374e-03,-2.985472e-03,-0.002198,-3.870004e-03,-4.438959e-03,-2.538045e-03,-1.280334e-03,-4.220525e-03,-0.003409,-1.474214e-03,0.002681,-0.007469
92,Expense,64220.0,Donations,-0.000029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Expense,64653.0,Electricity & gas,-0.004274,-0.003012,-1.804564e-03,-2.343694e-03,-0.001235,-3.062567e-03,-2.188683e-03,-6.242768e-03,-3.825441e-03,-3.372615e-03,-0.002233,-3.273371e-03,-0.003478,-0.002744
93,Expense,64230.0,Employee ammenities,-0.001292,-0.000330,-5.681103e-04,-2.796505e-04,-0.000243,-5.667635e-04,-1.018524e-03,-4.783348e-04,-1.131270e-03,-3.899440e-04,-0.000719,-3.198966e-04,-0.000984,-0.000189
77,Expense,63200.0,Entertainment,-0.002603,NaN,NaN,NaN,-0.000347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000331
78,Expense,63330.0,Establishment Fees,0.000161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,Expense,64250.0,"Filling fees,permits & licence",-0.000148,-0.000169,NaN,-3.053077e-04,-0.000313,-5.415374e-05,NaN,-2.957683e-04,NaN,NaN,-0.000440,-4.310883e-04,NaN,0.000228
66,Expense,64940.0,Fuel On Charge,-0.017172,0.005259,-9.479867e-19,1.543124e-18,0.000000,4.237155e-19,1.399716e-19,8.874645e-19,3.257514e-19,4.389346e-19,0.000000,-1.961452e-19,0.000000,NaN
61,Expense,64785.0,Human Resources,-0.011230,-0.000470,-3.230195e-03,-1.329263e-03,-0.000407,-1.890662e-04,-3.256181e-03,-2.596565e-04,-4.355284e-05,-2.544374e-04,-0.001460,-3.933681e-05,-0.000091,-0.000426
88,Expense,64182.0,IT Expense - Software,-0.006442,-0.008838,-9.063814e-03,-8.727085e-03,-0.007602,-7.160213e-03,-9.188933e-03,-9.705369e-03,-9.544860e-03,-8.896634e-03,-0.009289,-8.696518e-03,-0.010664,-0.009272
67,Expense,92000.0,Income Tax Expense,-0.055283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Expense,64282.0,Insurance Premium,-0.016820,-0.005134,-4.529107e-03,-4.754352e-03,-0.004083,-4.053640e-03,-4.804290e-03,-4.769950e-03,-4.668935e-03,-4.822595e-03,-0.004529,-4.216966e-03,NaN,-0.002309
70,Expense,64320.0,Interest - Bank,-0.000865,-0.016403,-1.446866e-02,-1.760418e-02,-0.013256,-1.256607e-02,-1.461405e-02,-1.614658e-02,-1.440985e-02,-1.420139e-02,-0.015235,-1.338718e-02,-0.009983,-0.002387
96,Expense,64300.0,Interest - Other,NaN,NaN,NaN,NaN,-0.000018,-1.699006e-05,NaN,NaN,NaN,-9.622798e-07,NaN,NaN,-0.000512,-0.008576
68,Expense,64400.0,Legal cost,-0.002852,-0.000038,NaN,-2.211406e-19,NaN,-7.541928e-19,-4.419480e-04,-1.126068e-04,-4.300992e-05,-5.422772e-03,0.005035,-3.077927e-04,0.000000,-0.000095
63,Expense,64851.0,Lines Phones,-0.004543,-0.003102,-3.181131e-03,-2.302837e-03,0.000383,-1.938061e-03,-2.164765e-03,-1.554366e-03,-2.020930e-03,-1.552968e-03,-0.001740,-1.680083e-03,-0.001997,-0.001052
76,Expense,63150.0,Management Consultant,NaN,-0.001440,-9.972774e-04,-1.110351e-03,-0.001270,-9.705498e-04,-1.448755e-03,-1.373367e-03,-1.277143e-03,-2.844369e-03,-0.000766,-5.252574e-04,-0.001631,-0.001135
53,Expense,64470.0,Medical costs,NaN,NaN,-4.169753e-05,NaN,-0.000071,-7.895300e-05,-2.729937e-04,NaN,3.271832e-05,9.745796e-05,NaN,-4.449586e-05,-0.000090,-0.000013
82,Expense,64108.0,Motor Vehical depreciation (64108),NaN,-0.000164,-2.137531e-04,-2.171455e-04,-0.000193,-1.851419e-04,-2.267405e-04,-2.251197e-04,-2.061362e-04,-2.226858e-04,-0.000207,-1.990216e-04,-0.000222,NaN
83,Expense,64109.0,Motor Vehicle Expense - Other,NaN,NaN,-9.102177e-05,NaN,-0.000276,-1.870875e-05,-4.516097e-04,-8.336680e-05,-1.041330e-05,-9.687071e-05,-0.000093,-1.293265e-05,NaN,-0.000330
57,Expense,69000.0,Other Head Offfice Expenses,NaN,NaN,-3.472826e-05,-4.638850e-05,-0.000009,-1.883617e-05,-8.451582e-05,-1.108233e-05,-1.483672e-04,-2.041746e-04,-0.000063,-3.978299e-05,-0.000023,-0.002194
46,Expense,64659.0,Other Property Cost,-0.017817,-0.025857,-2.319577e-02,-2.403854e-02,-0.020922,-2.303122e-02,-2.554800e-02,-2.608140e-02,-2.113003e-02,-3.946841e-02,-0.023295,-2.226735e-02,-0.043138,-0.017143
62,Expense,64788.0,Outsourced Services,-0.002082,-0.001996,-2.338701e-03,-2.459473e-03,-0.002119,-2.086447e-03,-2.458180e-03,-2.448508e-03,-2.410277e-03,-3.733120e-03,-0.002964,-3.243934e-03,-0.003117,-0.000971
58,Expense,64760.0,Payroll Tax HO,-0.000857,-0.000262,-2.314986e-04,-1.458070e-03,-0.003197,-1.756088e-03,-1.227821e-03,-1.219045e-03,-1.193228e-03,-1.205864e-03,-0.001157,-1.077721e-03,-0.001241,NaN
54,Expense,64660.0,Pest Control,-0.002756,-0.000896,-5.376960e-04,-7.814223e-04,-0.000759,-5.957077e-04,-7.301802e-04,-9.795157e-04,-5.072712e-04,-9.178546e-04,-0.000459,-6.497697e-04,-0.000854,-0.000124
90,Expense,64204.0,Plant & equipmant depreciation,-0.004686,-0.007889,-6.959034e-03,-7.070569e-03,-0.006306,-6.078052e-03,-7.462355e-03,-7.440603e-03,-6.844345e-03,-7.511284e-03,-0.007350,-7.095280e-03,-0.007940,-0.003884
50,Expense,64620.0,Printing & stationary,-0.002425,-0.001896,-1.019596e-03,-6.616940e-04,-0.001253,-1.289206e-03,-1.050842e-03,-1.187729e-03,-1.585418e-03,-7.726697e-04,-0.001307,-1.089166e-03,-0.000554,-0.000716
49,Expense,64656.0,Property Repairs,-0.000937,-0.000029,-5.631053e-04,NaN,-0.000074,NaN,NaN,-1.352201e-04,-4.490715e-05,-9.737379e-04,-0.000377,NaN,-0.000196,-0.000615
74,Expense,499.0,Realised Currency Gains,NaN,-0.000219,1.611462e-05,-1.002666e-04,-0.000321,-1.789903e-04,2.993747e-04,-1.442569e-04,-3.293633e-04,1.765627e-05,-0.000205,4.975837e-05,0.000103,0.000058
52,Expense,64651.0,Rent,-0.081301,-0.123474,-1.090473e-01,-1.147012e-01,-0.099174,-9.818713e-02,-1.163693e-01,-1.155376e-01,-1.130908e-01,-1.142884e-01,-0.109699,-1.026115e-01,-0.115562,-0.136943
56,Expense,64710.0,Salaries & Wages (64710),-0.026324,-0.032345,-3.519576e-02,-3.506203e-02,-0.031612,-3.324676e-02,-3.844691e-02,-4.237112e-02,-4.112401e-02,-4.555414e-02,-0.039580,-4.097487e-02,-0.042326,-0.046194
48,Expense,64657.0,Security,-0.000550,-0.000143,-3.014517e-04,-2.961717e-04,-0.000809,-3.369719e-04,-5.178605e-04,-5.234090e-04,-1.283919e-03,-3.219923e-04,-0.000489,-5.517392e-04,-0.000441,-0.000431
60,Expense,64775.0,Super Guarntee Charge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.555553e-04,NaN,NaN,NaN,NaN
59,Expense,64770.0,Superannuation HO,-0.002261,-0.003240,-3.696603e-03,-3.841739e-03,-0.003288,-3.559823e-03,-3.950468e-03,-4.547446e-03,-4.393282e-03,-4.280364e-03,-0.004354,-4.500935e-03,-0.004814,-0.002465
64,Expense,64870.0,Training,NaN,NaN,-1.538308e-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.000331
65,Expense,64880.0,Travel Costs,-0.000994,-0.000598,-3.606100e-04,-2.137409e-04,-0.000324,-1.267296e-03,-2.383668e-03,-2.692358e-04,-2.196459e-04,-1.977762e-04,-0.000510,-6.491220e-05,-0.000250,-0.000411
73,Expense,498.0,Unrealised Currency Gains,NaN,NaN,NaN,-8.770777e-05,NaN,NaN,4.899619e-04,NaN,-5.895801e-04,-7.018131e-07,0.000120,3.418617e-04,-0.000066,-0.000362
47,Expense,64658.0,Water,NaN,-0.000155,-2.101891e-05,-1.736987e-04,-0.000011,-2.213266e-05,-3.335130e-05,-2.704329e-05,-1.703596e-04,-4.662837e-05,-0.000014,-6.049247e-05,-0.000143,-0.000041

In [12]:
# Function to identify months, average them, and store the output in separate datasets
def process_df(df, columns_month):
    new_df = pd.DataFrame(columns=columns_month)
    
    # Non_month columns
    new_df[['account_type', 'account_code', 'account']] = df[['account_type', 'account_code', 'account']]
    
    # Identify same months and average them
    for month in ['january', 'february', 'march', 'april', 'may', 'june', 
                  'july', 'august', 'september', 'october', 'november', 'december']:
        month_columns = [col for col in df.columns if col.startswith(month)]
        
        if month_columns:
            new_df[month] = df[month_columns].mean(axis=1)
        else:
            new_df[month] = float('nan')
    
    return new_df

# Column names for the new DataFrames
columns_month = ['account_type', 'account_code', 'account', 'january', 'february', 'march', 'april', 'may', 'june', 
                 'july', 'august', 'september', 'october', 'november', 'december']

new_df_sales = process_df(sales_df_sorted, columns_month)
new_df_direct_costs = process_df(direct_costs_df_sorted, columns_month)
new_df_other_income = process_df(other_income_df_sorted, columns_month)
new_df_expense = process_df(expense_df_sorted, columns_month)

In [13]:
new_df_expense

,account_type,account_code,account,january,february,march,april,may,june,july,august,september,october,november,december
80,Expense,64010.0,Accounting Fees Expense,-2.900107e-03,-1.239466e-03,NaN,-0.001716,-3.394821e-04,-0.005465,-0.001075,-1.360054e-03,-2.065599e-03,-0.001458,-1.077418e-03,-1.838969e-03
75,Expense,63100.0,Advertising,-3.505152e-03,-4.690274e-03,-5.167777e-03,-0.002975,-2.915807e-03,-0.004686,-0.002336,-1.041744e-03,-1.161900e-03,-0.000949,-9.323812e-04,-1.217044e-03
79,Expense,63510.0,Amortisation (63510),-1.523806e-04,-1.491536e-04,-1.507331e-04,-0.000145,-1.347151e-04,-0.000158,-0.000213,-1.446866e-04,-1.518823e-04,-0.000130,-1.294974e-04,-1.534776e-04
89,Expense,64184.0,Asset <$300 or 2yr Eff Life,-1.432889e-04,NaN,NaN,NaN,NaN,NaN,-0.000275,-4.677429e-04,-3.444116e-03,NaN,NaN,-2.400856e-04
81,Expense,64011.0,Audit Fees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.794634e-03,-0.004299,NaN,-1.271987e-03
87,Expense,64140.0,Bad debts,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,-0.000129,NaN,NaN
84,Expense,64130.0,Bank Charges,-1.053864e-04,-1.095348e-04,-2.641446e-05,-0.000054,-4.849744e-06,-0.000004,-0.001211,-5.666044e-05,-9.111237e-05,-0.000010,-2.744930e-05,-1.111178e-05
95,Expense,497.0,Bank Revaluations,NaN,4.623641e-04,-6.772376e-05,0.000085,-1.566898e-04,0.000032,-0.000008,NaN,1.668657e-03,NaN,NaN,-6.591753e-04
85,Expense,64132.0,Bank account fees,-3.438484e-03,-3.325687e-03,-3.266283e-03,-0.003103,-2.994156e-03,-0.004760,-0.001336,-2.124855e-03,-2.293774e-03,-0.001963,-1.954161e-03,-3.314751e-03
86,Expense,64138.0,Bank merchant fees,-1.175878e-04,-1.133639e-04,-3.080622e-05,-0.000264,-9.877850e-05,-0.000103,-0.000129,-1.863193e-04,-1.855734e-04,-0.000173,-3.036662e-05,-3.354529e-05
69,Expense,64740.0,Car Allowances - HO,NaN,NaN,NaN,NaN,NaN,-0.000082,NaN,NaN,NaN,NaN,NaN,NaN
51,Expense,64652.0,Cleaning,-2.690568e-03,-2.717895e-03,-2.373607e-03,-0.003254,-2.445811e-03,-0.004070,-0.001996,-2.171449e-03,-4.647557e-03,-0.002382,-2.721341e-03,-2.821773e-03
71,Expense,64160.0,Collection costs,-8.768222e-05,-8.582534e-05,-8.673421e-05,-0.000083,-7.751722e-05,-0.000202,-0.000096,-8.325499e-05,-8.739550e-05,-0.000124,-7.451487e-05,-8.831347e-05
91,Expense,64210.0,Director's Fees,-2.538045e-03,-1.280334e-03,-4.220525e-03,-0.003409,-1.474214e-03,-0.000802,-0.006180,-4.721374e-03,-2.985472e-03,-0.002198,-3.870004e-03,-4.438959e-03
92,Expense,64220.0,Donations,NaN,NaN,NaN,NaN,NaN,-0.000029,NaN,NaN,NaN,NaN,NaN,NaN
55,Expense,64653.0,Electricity & gas,-6.242768e-03,-3.825441e-03,-3.372615e-03,-0.002233,-3.273371e-03,-0.003876,-0.002878,-1.804564e-03,-2.343694e-03,-0.001235,-3.062567e-03,-2.188683e-03
93,Expense,64230.0,Employee ammenities,-4.783348e-04,-1.131270e-03,-3.899440e-04,-0.000719,-3.198966e-04,-0.001138,-0.000259,-5.681103e-04,-2.796505e-04,-0.000243,-5.667635e-04,-1.018524e-03
77,Expense,63200.0,Entertainment,NaN,NaN,NaN,NaN,NaN,-0.002603,-0.000331,NaN,NaN,-0.000347,NaN,NaN
78,Expense,63330.0,Establishment Fees,NaN,NaN,NaN,NaN,NaN,0.000161,NaN,NaN,NaN,NaN,NaN,NaN
94,Expense,64250.0,"Filling fees,permits & licence",-2.957683e-04,NaN,NaN,-0.000440,-4.310883e-04,-0.000148,0.000030,NaN,-3.053077e-04,-0.000313,-5.415374e-05,NaN
66,Expense,64940.0,Fuel On Charge,8.874645e-19,3.257514e-19,4.389346e-19,0.000000,-1.961452e-19,-0.008586,0.005259,-9.479867e-19,1.543124e-18,0.000000,4.237155e-19,1.399716e-19
61,Expense,64785.0,Human Resources,-2.596565e-04,-4.355284e-05,-2.544374e-04,-0.001460,-3.933681e-05,-0.005660,-0.000448,-3.230195e-03,-1.329263e-03,-0.000407,-1.890662e-04,-3.256181e-03
88,Expense,64182.0,IT Expense - Software,-9.705369e-03,-9.544860e-03,-8.896634e-03,-0.009289,-8.696518e-03,-0.008553,-0.009055,-9.063814e-03,-8.727085e-03,-0.007602,-7.160213e-03,-9.188933e-03
67,Expense,92000.0,Income Tax Expense,NaN,NaN,NaN,NaN,NaN,-0.055283,NaN,NaN,NaN,NaN,NaN,NaN
72,Expense,64282.0,Insurance Premium,-4.769950e-03,-4.668935e-03,-4.822595e-03,-0.004529,-4.216966e-03,-0.016820,-0.003722,-4.529107e-03,-4.754352e-03,-0.004083,-4.053640e-03,-4.804290e-03
70,Expense,64320.0,Interest - Bank,-1.614658e-02,-1.440985e-02,-1.420139e-02,-0.015235,-1.338718e-02,-0.005424,-0.009395,-1.446866e-02,-1.760418e-02,-0.013256,-1.256607e-02,-1.461405e-02
96,Expense,64300.0,Interest - Other,NaN,NaN,-9.622798e-07,NaN,NaN,-0.000512,-0.008576,NaN,NaN,-0.000018,-1.699006e-05,NaN
68,Expense,64400.0,Legal cost,-1.126068e-04,-4.300992e-05,-5.422772e-03,0.005035,-3.077927e-04,-0.001426,-0.000066,NaN,-2.211406e-19,NaN,-7.541928e-19,-4.419480e-04
63,Expense,64851.0,Lines Phones,-1.554366e-03,-2.020930e-03,-1.552968e-03,-0.001740,-1.680083e-03,-0.003270,-0.002077,-3.181131e-03,-2.302837e-03,0.000383,-1.938061e-03,-2.164765e-03
76,Expense,63150.0,Management Consultant,-1.373367e-03,-1.277143e-03,-2.844369e-03,-0.000766,-5.252574e-04,-0.001631,-0.001287,-9.972774e-04,-1.110351e-03,-0.001270,-9.705498e-04,-1.448755e-03
53,Expense,64470.0,Medical costs,NaN,3.271832e-05,9.745796e-05,NaN,-4.449586e-05,-0.000090,-0.000013,-4.169753e-05,NaN,-0.000071,-7.895300e-05,-2.729937e-04
82,Expense,64108.0,Motor Vehical depreciation (64108),-2.251197e-04,-2.061362e-04,-2.226858e-04,-0.000207,-1.990216e-04,-0.000222,-0.000164,-2.137531e-04,-2.171455e-04,-0.000193,-1.851419e-04,-2.267405e-04
83,Expense,64109.0,Motor Vehicle Expense - Other,-8.336680e-05,-1.041330e-05,-9.687071e-05,-0.000093,-1.293265e-05,NaN,-0.000330,-9.102177e-05,NaN,-0.000276,-1.870875e-05,-4.516097e-04
57,Expense,69000.0,Other Head Offfice Expenses,-1.108233e-05,-1.483672e-04,-2.041746e-04,-0.000063,-3.978299e-05,-0.000023,-0.002194,-3.472826e-05,-4.638850e-05,-0.000009,-1.883617e-05,-8.451582e-05
46,Expense,64659.0,Other Property Cost,-2.608140e-02,-2.113003e-02,-3.946841e-02,-0.023295,-2.226735e-02,-0.030478,-0.021500,-2.319577e-02,-2.403854e-02,-0.020922,-2.303122e-02,-2.554800e-02
62,Expense,64788.0,Outsourced Services,-2.448508e-03,-2.410277e-03,-3.733120e-03,-0.002964,-3.243934e-03,-0.002600,-0.001484,-2.338701e-03,-2.459473e-03,-0.002119,-2.086447e-03,-2.458180e-03
58,Expense,64760.0,Payroll Tax HO,-1.219045e-03,-1.193228e-03,-1.205864e-03,-0.001157,-1.077721e-03,-0.001049,-0.000262,-2.314986e-04,-1.458070e-03,-0.003197,-1.756088e-03,-1.227821e-03
54,Expense,64660.0,Pest Control,-9.795157e-04,-5.072712e-04,-9.178546e-04,-0.000459,-6.497697e-04,-0.001805,-0.000510,-5.376960e-04,-7.814223e-04,-0.000759,-5.957077e-04,-7.301802e-04
90,Expense,64204.0,Plant & equipmant depreciation,-7.440603e-03,-6.844345e-03,-7.511284e-03,-0.007350,-7.095280e-03,-0.006313,-0.005887,-6.959034e-03,-7.070569e-03,-0.006306,-6.078052e-03,-7.462355e-03
50,Expense,64620.0,Printing & stationary,-1.187729e-03,-1.585418e-03,-7.726697e-04,-0.001307,-1.089166e-03,-0.001490,-0.001306,-1.019596e-03,-6.616940e-04,-0.001253,-1.289206e-03,-1.050842e-03
49,Expense,64656.0,Property Repairs,-1.352201e-04,-4.490715e-05,-9.737379e-04,-0.000377,NaN,-0.000567,-0.000322,-5.631053e-04,NaN,-0.000074,NaN,NaN
74,Expense,499.0,Realised Currency Gains,-1.442569e-04,-3.293633e-04,1.765627e-05,-0.000205,4.975837e-05,0.000103,-0.000081,1.611462e-05,-1.002666e-04,-0.000321,-1.789903e-04,2.993747e-04
52,Expense,64651.0,Rent,-1.155376e-01,-1.130908e-01,-1.142884e-01,-0.109699,-1.026115e-01,-0.098431,-0.130209,-1.090473e-01,-1.147012e-01,-0.099174,-9.818713e-02,-1.163693e-01
56,Expense,64710.0,Salaries & Wages (64710),-4.237112e-02,-4.112401e-02,-4.555414e-02,-0.039580,-4.097487e-02,-0.034325,-0.039270,-3.519576e-02,-3.506203e-02,-0.031612,-3.324676e-02,-3.844691e-02
48,Expense,64657.0,Security,-5.234090e-04,-1.283919e-03,-3.219923e-04,-0.000489,-5.517392e-04,-0.000495,-0.000287,-3.014517e-04,-2.961717e-04,-0.000809,-3.369719e-04,-5.178605e-04
60,Expense,64775.0,Super Guarntee Charge,NaN,NaN,-1.555553e-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Expense,64770.0,Superannuation HO,-4.547446e-03,-4.393282e-03,-4.280364e-03,-0.004354,-4.500935e-03,-0.003537,-0.002853,-3.696603e-03,-3.841739e-03,-0.003288,-3.559823e-03,-3.950468e-03
64,Expense,64870.0,Training,NaN,NaN,NaN,NaN,NaN,NaN,-0.000331,-1.538308e-04,NaN,NaN,NaN,NaN
65,Expense,64880.0,Travel Costs,-2.692358e-04,-2.196459e-04,-1.977762e-04,-0.000510,-6.491220e-05,-0.000622,-0.000505,-3.606100e-04,-2.137409e-04,-0.000324,-1.267296e-03,-2.383668e-03
73,Expense,498.0,Unrealised Currency Gains,NaN,-5.895801e-04,-7.018131e-07,0.000120,3.418617e-04,-0.000066,-0.000362,NaN,-8.770777e-05,NaN,NaN,4.899619e-04
47,Expense,64658.0,Water,-2.704329e-05,-1.703596e-04,-4.662837e-05,-0.000014,-6.049247e-05,-0.000143,-0.000098,-2.101891e-05,-1.736987e-04,-0.000011,-2.213266e-05,-3.335130e-05

In [11]:
# new_df_direct_costs

# columns_to_sum_2 = new_df_direct_costs.columns[3:]
# column_sums_2 = new_df_direct_costs[columns_to_sum_2].sum()
# print(column_sums_2)

In [15]:
# Corresponding month and year
future_months = [
    'august_2024', 'september_2024', 'october_2024', 'november_2024', 'december_2024',
    'january_2025', 'february_2025', 'march_2025', 'april_2025', 'may_2025',
    'june_2025', 'july_2025', 'august_2025', 'september_2025', 'october_2025',
    'november_2025', 'december_2025', 'january_2026', 'february_2026', 'march_2026',
    'april_2026', 'may_2026', 'june_2026', 'july_2026', 'august_2026',
    'september_2026', 'october_2026', 'november_2026', 'december_2026',
    'january_2027', 'february_2027', 'march_2027', 'april_2027', 'may_2027',
    'june_2027', 'july_2027'
]

In [13]:
# # Function to multiply the percentages by the corresponding revenue forecast
# def multiply_forecast_with_percentage(new_df, df_revenue_forecast):
    
#     # Normalize month names
#     df_revenue_forecast['Month'] = df_revenue_forecast['Month'].str.strip().str.lower()
#     new_df.columns = new_df.columns.str.strip().str.lower()

#     result_df = pd.DataFrame(columns=['account_type', 'account_code', 'account'] + list(df_revenue_forecast['Month']))
#     result_df[['account_type', 'account_code', 'account']] = new_df[['account_type', 'account_code', 'account']]
    
#     for i, row in result_df.iterrows():
#         # Iterate over each month_year column in result_df starting from the 4th col
#         for col in result_df.columns[3:]:
#             # Extract the month part 
#             month_part = col.split('_')[0]
            
#             if month_part in new_df.columns:
#                 # Find the corresponding forecast value from df_revenue_forecast
#                 forecast_value = df_revenue_forecast.loc[df_revenue_forecast['Month'] == col, 'Revenue Forecast'].values[0]

#                 result_df.at[i, col] = new_df.at[i, month_part] * forecast_value
#             else:
#                 # Fill with NaN if no corresponding value
#                 result_df.at[i, col] = float('nan')

#     return result_df

# new_sales_forecast = multiply_forecast_with_percentage(new_df_sales, df_revenue_forecast)
# new_direct_costs_forecast = multiply_forecast_with_percentage(new_df_direct_costs, df_revenue_forecast)
# new_other_income_forecast = multiply_forecast_with_percentage(new_df_other_income, df_revenue_forecast)
# new_expense_forecast = multiply_forecast_with_percentage(new_df_expense, df_revenue_forecast)

In [16]:
gl_df = pd.read_excel('/Users/zhengyaojin/Desktop/GL_June_2023_to_July_2024_Brien v7.xlsx')

In [19]:
# Yash's forecast
rev_forecast = gl_df[(gl_df['Account Type'] == 'Sales') & (gl_df['Status'] == 'CP Forecast')]
rev_forecast

,Date,Account Code,Account Type,Account,Source,Description,Invoice Number,Reference,Journal ID,Debit,Credit,Gross,GST,Net,GST Rate,GST Rate Name,Cost Centre,Amount,Unique ID,Status
380774,2024-07-28,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.147405e+06,380775,CP Forecast
380775,2024-08-04,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.968866e+06,380776,CP Forecast
380776,2024-08-11,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.549176e+06,380777,CP Forecast
380777,2024-08-18,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.865819e+06,380778,CP Forecast
380778,2024-08-25,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.914740e+06,380779,CP Forecast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380927,2027-07-04,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.455317e+06,380928,CP Forecast
380928,2027-07-11,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.485165e+06,380929,CP Forecast
380929,2027-07-18,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.230670e+06,380930,CP Forecast
380930,2027-07-25,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.722722e+05,380931,CP Forecast
380931,2027-08-01,100000,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.490011e+05,380932,CP Forecast

In [25]:
# Group by month
rev_forecast['Date'] = pd.to_datetime(rev_forecast['Date'])

monthly_forecast = rev_forecast.groupby(pd.Grouper(key='Date', freq='M')).agg({
    'Amount': 'sum',
    'Account Type': 'first',  
    'Status': 'first',        
}).reset_index()

# Convert the 'Date' column to datetime format if it's not already
monthly_forecast['Date'] = pd.to_datetime(monthly_forecast['Date'])

# Format the 'Date' column to the desired 'month_year' format
monthly_forecast['Month'] = monthly_forecast['Date'].dt.strftime('%B_%Y').str.lower()

monthly_forecast = monthly_forecast.drop(columns=['Account Type', 'Status'])

# Rename 
monthly_forecast = monthly_forecast.rename(columns={'Amount': 'Revenue Forecast'})

monthly_forecast = monthly_forecast.drop(columns=['Date'])
monthly_forecast = monthly_forecast[['Month', 'Revenue Forecast']]

monthly_forecast

/var/folders/49/pxgfdjk93j37m84dbmvq4ndh0000gn/T/ipykernel_91201/2147915256.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rev_forecast['Date'] = pd.to_datetime(rev_forecast['Date'])

             Month  Revenue Forecast
0        july_2024      2.147405e+06
1      august_2024      7.298602e+06
2   september_2024      9.264504e+06
3     october_2024      8.119347e+06
4    november_2024      8.024278e+06
5    december_2024      9.792739e+06
6     january_2025      6.344520e+06
7    february_2025      7.478634e+06
8       march_2025      9.308680e+06
9       april_2025      7.525359e+06
10        may_2025      7.399787e+06
11       june_2025      8.680383e+06
12       july_2025      5.735297e+06
13     august_2025      7.604821e+06
14  september_2025      6.977756e+06
15    october_2025      7.596668e+06
16   november_2025      9.773539e+06
17   december_2025      7.189028e+06
18    january_2026      5.752350e+06
19   february_2026      7.009375e+06
20      march_2026      8.745510e+06
21      april_2026      7.032517e+06
22        may_2026      8.853283e+06
23       june_2026      6.227996e+06
24       july_2026      5.393342e+06
25     august_2026      6.901865e+06
26  september_2026      6.476383e+06
27    october_2026      7.076301e+06
28   november_2026      9.158066e+06
29   december_2026      6.948949e+06
30    january_2027      6.795847e+06
31   february_2027      6.561092e+06
32      march_2027      6.526231e+06
33      april_2027      6.537967e+06
34        may_2027      8.252149e+06
35       june_2027      5.839099e+06
36       july_2027      5.043425e+06
37     august_2027      7.490011e+05

In [26]:
# data_combined_sales = {
#     'Date': [
#         'june_2023', 'july_2023', 'august_2023', 'september_2023', 'october_2023', 'november_2023', 'december_2023',
#         'january_2024', 'february_2024', 'march_2024', 'april_2024', 'may_2024', 'june_2024', 'july_2024',
#         'august_2024', 'september_2024', 'october_2024', 'november_2024', 'december_2024',
#         'january_2025', 'february_2025', 'march_2025', 'april_2025', 'may_2025', 'june_2025', 'july_2025',
#         'august_2025', 'september_2025', 'october_2025', 'november_2025', 'december_2025',
#         'january_2026', 'february_2026', 'march_2026', 'april_2026', 'may_2026', 'june_2026', 'july_2026',
#         'august_2026', 'september_2026', 'october_2026', 'november_2026', 'december_2026',
#         'january_2027', 'february_2027', 'march_2027', 'april_2027', 'may_2027', 'june_2027', 'july_2027',
#         'august_2027', 'september_2027'
#     ],
#     'Sales': [
#         2333799, 7620739, 8639362, 8230057, 9583309, 9652704, 8144510, 8203145, 8380625, 8292806,
#         8639735, 9278841, 8059366, 15091620, 2147405, 7298602, 9264504, 8119347, 8024278, 9792739,
#         6344520, 7478634, 9308680, 7525359, 7399787, 8680383, 5735297, 7604821, 6977756, 7596668,
#         9773539, 7189028, 5752350, 7009375, 8745510, 7032517, 8853283, 6227996, 5393342, 6901865,
#         6476383, 7076301, 9158066, 6948949, 6795847, 6561092, 6526231, 6537967, 8252149, 5839099,
#         5043425, 749001
#     ]
# }

# # Create a DataFrame for the combined sales data
# df_combined_sales = pd.DataFrame(data_combined_sales)

# # Plotting the combined sales data
# plt.figure(figsize=(14, 7))
# plt.plot(df_combined_sales['Date'], df_combined_sales['Sales'], marker='o', linestyle='-', color='green')

# # Adding title and labels
# plt.title('Monthly Sales Over Time - Combined Dataset')
# plt.xlabel('Date')
# plt.ylabel('Sales')
# plt.xticks(rotation=90)  # Rotate x-axis labels for better readability

# # Change y-axis to use standard notation
# plt.ticklabel_format(style='plain', axis='y')

# # Display the plot
# plt.grid(True)
# plt.tight_layout()
# plt.show()

In [27]:
# Function to multiply the percentages by the corresponding revenue forecast
def multiply_forecast_with_percentage(new_df, df_revenue_forecast):
    
    # Normalize month names
    df_revenue_forecast['Month'] = df_revenue_forecast['Month'].str.strip().str.lower()
    new_df.columns = new_df.columns.str.strip().str.lower()

    result_df = pd.DataFrame(columns=['account_type', 'account_code', 'account'] + list(df_revenue_forecast['Month']))
    result_df[['account_type', 'account_code', 'account']] = new_df[['account_type', 'account_code', 'account']]
    
    for i, row in result_df.iterrows():
        # Iterate over each month_year column in result_df starting from the 4th col
        for col in result_df.columns[3:]:
            # Extract the month part 
            month_part = col.split('_')[0]
            
            if month_part in new_df.columns:
                # Find the corresponding forecast value from df_revenue_forecast
                forecast_value = df_revenue_forecast.loc[df_revenue_forecast['Month'] == col, 'Revenue Forecast'].values[0]

                result_df.at[i, col] = new_df.at[i, month_part] * forecast_value
            else:
                # Fill with NaN if no corresponding value
                result_df.at[i, col] = float('nan')

    return result_df

new_sales_forecast = multiply_forecast_with_percentage(new_df_sales, monthly_forecast)
new_direct_costs_forecast = multiply_forecast_with_percentage(new_df_direct_costs, monthly_forecast)
new_other_income_forecast = multiply_forecast_with_percentage(new_df_other_income, monthly_forecast)
new_expense_forecast = multiply_forecast_with_percentage(new_df_expense, monthly_forecast)

In [29]:
#new_expense_forecast

In [18]:
# new_sales_forecast
# new_direct_costs_forecast
# new_other_income_forecast
# new_expense_forecast

# columns_to_sum_3 = new_sales_forecast.columns[3:]
# column_sums_3 = new_sales_forecast[columns_to_sum_3].sum()
# print(column_sums_3)

In [36]:
#new_expense_forecast

,account_type,account_code,account,august_2024,september_2024,october_2024,november_2024,december_2024,january_2025,february_2025,...,december_2026,january_2027,february_2027,march_2027,april_2027,may_2027,june_2027,july_2027,august_2027,september_2027
80,Expense,64010.0,Accounting Fees Expense,-2920.587449,-15075.986348,-13510.097471,-8747.933069,-14756.396831,-28399.991772,-7863.816695,...,-16841.396943,-20152.695882,-8423.220742,NaN,-11198.420381,-2219.52245,-45101.953336,-6274.201931,-6859.330935,-1547.136129
75,Expense,63100.0,Advertising,-2237.045705,-8480.242321,-8788.485166,-7570.326694,-9765.902144,-34325.03705,-29757.537838,...,-11145.771992,-24357.120888,-31874.383605,-33906.259465,-19417.645486,-19063.450139,-38673.088746,-13642.200205,-5253.95561,-870.264073
79,Expense,63510.0,Amortisation (63510),-310.700792,-1108.528408,-1208.41659,-1051.434263,-1231.547056,-1492.223191,-946.307665,...,-1405.558082,-1058.884819,-1013.624638,-988.973478,-944.21757,-880.762877,-1302.936918,-1245.093918,-729.716057,-113.760009
89,Expense,64184.0,Asset <$300 or 2yr Eff Life,-1004.433522,-25137.22962,NaN,NaN,-1926.513987,-1403.191187,NaN,...,-2198.72013,-995.707516,NaN,NaN,NaN,NaN,NaN,-1606.056223,-2359.026069,-2579.646547
81,Expense,64011.0,Audit Fees,NaN,-20396.922706,-39824.403112,NaN,-10206.776285,NaN,NaN,...,-11648.939297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2093.184175
87,Expense,64140.0,Bad debts,NaN,NaN,-1196.902796,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
84,Expense,64130.0,Bank Charges,-121.672916,-664.99289,-92.323027,-222.870418,-89.164007,-1032.021559,-694.945638,...,-101.762405,-732.324741,-744.381607,-173.307712,-355.025806,-31.707464,-33.963434,-7071.813432,-285.762646,-68.243265
95,Expense,497.0,Bank Revaluations,NaN,12178.860656,NaN,NaN,-5289.405936,NaN,2933.478057,...,-6036.770763,NaN,3142.155288,-444.341828,555.592726,-1024.432918,263.188459,-46.270558,NaN,1249.825709
85,Expense,64132.0,Bank account fees,-4562.924496,-16741.341877,-18183.01542,-15866.513135,-26598.480412,-33672.171497,-21099.890139,...,-30356.703728,-23893.846073,-22600.861536,-21430.382772,-20253.791689,-19575.694782,-39283.235152,-7803.319255,-10716.545796,-1718.039157
86,Expense,64138.0,Bank merchant fees,-400.103081,-1354.426613,-1607.377743,-246.557129,-269.176777,-1151.506854,-719.239248,...,-307.210019,-817.111766,-770.403379,-202.122444,-1723.076206,-645.810572,-845.932188,-754.055322,-939.687474,-138.99471
69,Expense,64740.0,Car Allowances - HO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-679.994587,NaN,NaN,NaN
51,Expense,64652.0,Cleaning,-4662.980093,-33920.667763,-22069.863212,-22095.512522,-22642.692152,-26348.029693,-17243.739398,...,-25841.983701,-18696.619132,-18470.397899,-15573.452392,-21236.193418,-15990.630522,-33586.922122,-11653.388634,-10951.537718,-3481.025348
71,Expense,64160.0,Collection costs,-178.782207,-637.864982,-1148.121435,-605.012098,-708.651881,-858.6491,-544.520571,...,-808.78061,-609.299267,-583.255835,-569.071163,-543.317897,-506.805052,-1667.209965,-562.399345,-419.890295,-65.45933
91,Expense,64210.0,Director's Fees,-10138.703747,-21789.775348,-20359.4027,-31421.902665,-35619.444372,-24854.409781,-8123.104996,...,-40652.281747,-17636.743196,-8700.953893,-27691.257392,-22245.765952,-9638.364316,-6618.446613,-36086.694512,-23811.895885,-2236.122262
92,Expense,64220.0,Donations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-240.443201,NaN,NaN,NaN
55,Expense,64653.0,Electricity & gas,-3875.12988,-17105.692994,-11438.426739,-24866.041805,-17562.599954,-61133.793638,-24270.588601,...,-20044.101589,-43380.672826,-25997.112248,-22128.036311,-14574.881982,-21401.192106,-31986.570288,-16805.442218,-9101.182118,-1755.429796
93,Expense,64230.0,Employee ammenities,-1219.962933,-2041.057978,-2247.509846,-4601.749253,-8172.920657,-4684.207975,-7177.365115,...,-9327.710724,-3323.924159,-7687.93743,-2558.458565,-4689.256388,-2091.47362,-9392.523778,-1513.797852,-2865.221341,-209.45857
77,Expense,63200.0,Entertainment,NaN,NaN,-3219.221794,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-21480.771226,-1934.549609,NaN,NaN
78,Expense,63330.0,Establishment Fees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1325.973532,NaN,NaN,NaN
94,Expense,64250.0,"Filling fees,permits & licence",NaN,-2228.319464,-2900.199815,-439.692986,NaN,-2896.381338,NaN,...,NaN,-2055.278492,NaN,NaN,-2872.687535,-2818.441206,-1219.89565,173.19789,NaN,-228.675821
66,Expense,64940.0,Fuel On Charge,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,-0.0,-70852.016696,30706.284012,-0.0,0.0
61,Expense,64785.0,Human Resources,-6936.53687,-9701.760812,-3771.912873,-1535.094024,-26128.50235,-2542.748318,-276.321838,...,-29820.320275,-1804.339732,-295.978394,-1669.387231,-9529.043717,-257.18276,-46708.991999,-2618.286692,-16291.24372,-995.619412
88,Expense,64182.0,IT Expense - Software,-19463.68212,-63695.519094,-70424.198676,-58136.256555,-73734.554814,-95042.142284,-60557.550911,...,-84152.85386,-67442.110717,-64865.400439,-58371.635695,-60621.97834,-56857.54888,-70580.383812,-52871.571672,-45712.665418,-6536.596451
67,Expense,92000.0,Income Tax Expense,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-456205.967355,NaN,NaN,NaN
72,Expense,64282.0,Insurance Premium,-9725.827135,-34700.122862,-37826.909824,-32912.912153,-38550.959871,-46710.871545,-29622.147708,...,-43998.00474,-33146.135964,-31729.362301,-31641.494376,-29556.721737,-27570.386463,-138801.777883,-21732.214362,-22842.208325,-3561.015016
70,Expense,64320.0,Interest - Bank,-31070.071785,-128485.927262,-122806.515323,-102028.245284,-117267.221052,-158119.27609,-91423.608688,...,-133836.453487,-112201.78195,-97927.160164,-93176.626786,-99427.326284,-87524.923093,-44759.037186,-54857.00732,-72971.588175,-13185.553208
96,Expense,64300.0,Interest - Other,NaN,NaN,-166.674483,-137.948175,NaN,NaN,NaN,...,NaN,NaN,NaN,-6.313607,NaN,NaN,-4221.459337,-50075.713089,NaN,NaN
68,Expense,64400.0,Legal cost,NaN,-0.0,NaN,-0.0,-3546.313642,-1102.729063,-272.877278,...,-4047.388832,-782.498939,-292.288801,-35579.309854,32856.55064,-2012.338837,-11767.57311,-386.321939,NaN,-0.0
63,Expense,64851.0,Lines Phones,-6831.176989,-16807.489984,3549.254866,-15735.790415,-17370.67566,-15221.500256,-12821.832941,...,-19825.059417,-10801.209662,-13733.93269,-10189.164305,-11357.72877,-10984.325006,-26986.343559,-12127.793739,-16043.794087,-1724.827444
76,Expense,63150.0,Management Consultant,-2141.558652,-8104.007779,-11762.30172,-7880.230635,-11625.213071,-13449.025612,-8102.861582,...,-13267.793629,-9543.457803,-8679.270435,-18662.166889,-5002.321165,-3434.115596,-13456.810365,-7517.403845,-5029.693433,-831.653925
53,Expense,64470.0,Medical costs,-89.541483,NaN,-659.737454,-641.046853,-2190.57738,NaN,207.582049,...,-2500.094272,NaN,222.348701,639.430692,NaN,-290.912455,-744.666475,-77.381984,-210.29833,NaN
82,Expense,64108.0,Motor Vehical depreciation (64108),-459.014437,-1584.858631,-1785.256665,-1503.23136,-1819.428507,-2204.538916,-1307.835045,...,-2076.504044,-1564.345606,-1400.869795,-1461.061946,-1349.944083,-1301.196798,-1829.868346,-958.51544,-1078.047476,-162.642231
83,Expense,64109.0,Motor Vehicle Expense - Other,-195.460626,NaN,-2558.101912,-151.902811,-3623.841992,-816.389339,-66.067416,...,-4135.871524,-579.311649,-70.767218,-635.577651,-605.386984,-84.553236,NaN,-1926.381375,-459.061453,NaN
57,Expense,69000.0,Other Head Offfice Expenses,-74.575647,-338.57118,-87.885722,-152.937422,-678.178481,-108.526408,-941.318731,...,-774.00148,-77.010575,-1008.280809,-1339.608091,-412.026333,-260.099847,-186.169179,-12810.456448,-175.149367,-34.745037
46,Expense,64659.0,Other Property Cost,-49810.718362,-175447.740022,-193830.36898,-186998.45848,-205004.298408,-255408.336428,-134059.879054,...,-233970.311587,-181238.310602,-143596.423681,-258955.916971,-152029.43784,-145583.17725,-251505.098261,-125541.057194,-116986.122599,-18004.894081
62,Expense,64788.0,Outsourced Services,-5022.137781,-17950.710897,-19632.67063,-16940.591086,-19725.117766,-23977.60331,-15292.051758,...,-22512.171626,-17014.559418,-16379.874118,-24493.344399,-19346.965135,-21208.734848,-21455.009612,-8664.048958,-11795.060291,-1842.147687
58,Expense,64760.0,Payroll Tax HO,-497.121268,-10641.872716,-29621.674175,-14258.289755,-9852.376452,-11937.785528,-7570.461319,...,-11244.464659,-8471.078555,-8108.997104,-7911.787826,-7553.740561,-7046.103016,-8655.530637,-1532.423284,-1167.545691,-1092.096091
54,Expense,64660.0,Pest Control,-1154.651141,-5703.289976,-7032.414178,-4836.757428,-5859.168866,-9592.141988,-3218.392368,...,-6687.038155,-6806.604801,-3447.337394,-6022.12851,-2998.540407,-4248.173015,-14895.402615,-2977.241557,-2711.829188,-585.286148
90,Expense,64204.0,Plant & equipmant depreciation,-14943.865495,-51605.269765,-58419.333912,-49349.815758,-59880.014966,-72863.885573,-43424.082853,...,-68340.741479,-51704.371556,-46513.118192,-49282.225721,-47969.251396,-46388.709724,-52097.385756,-34373.430586,-35097.363346,-5295.864262
50,Expense,64620.0,Printing & stationary,-2189.486114,-4829.441467,-11611.762015,-10467.507543,-8432.245058,-11631.115756,-10058.712975,...,-9623.676278,-8253.465018,-10774.254164,-5069.557167,-8531.119052,-7120.93263,-12293.846744,-7625.288309,-5142.256513,-495.609588
49,Expense,64656.0,Property Repairs,-1209.215171,NaN,-685.384888,NaN,NaN,-1324.174984,-284.914312,...,NaN,-939.637447,-305.182106,-6388.784493,-2457.700136,NaN,-4674.952728,-1879.4659,-2839.979003,NaN
74,Expense,499.0,Realised Currency Gains,34.604611,-731.806114,-2977.673819,-1453.284027,2402.265541,-1412.669788,-2089.651727,...,2741.69284,-1002.433552,-2238.302144,115.844397,-1334.829048,325.318576,848.696772,-471.317865,81.272856,-75.099808
52,Expense,64651.0,Rent,-234168.67744,-837158.729259,-918797.483307,-797215.383109,-933779.983493,-1131429.074809,-717506.619335,...,-1065718.111223,-802864.530393,-768547.497067,-749856.57498,-715921.97953,-670870.579861,-812271.033792,-760301.080133,-549971.703057,-85911.361683
56,Expense,64710.0,Salaries & Wages (64710),-75579.551086,-255903.818442,-292868.383727,-269942.002694,-308508.71509,-414929.275668,-260912.080865,...,-352099.349904,-294434.71577,-279472.441508,-298884.890419,-258307.953936,-267892.336396,-283257.605351,-229299.358964,-177507.149468,-26261.501832
48,Expense,64657.0,Security,-647.338887,-2161.639264,-7497.557892,-2735.991771,-4155.456521,-5125.607594,-8145.846661,...,-4742.600348,-3637.142288,-8725.31332,-2112.621409,-3189.423431,-3607.252439,-4086.855139,-1674.807746,-1520.34881,-221.832929
60,Expense,64775.0,Super Guarntee Charge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-1020.612718,NaN,NaN,NaN,NaN,NaN,NaN
59,Expense,64770.0,Superannuation HO,-7938.104488,-28039.321519,-30457.511762,-28903.440026,-31699.656696,-44531.951117,-27873.265156,...,-36178.648994,-31599.969293,-29856.070444,-28083.864039,-28413.90122,-29426.964147,-29190.892661,-16656.896766,-18643.538888,-2877.466612
64,Expense,64870.0,Training,-330.337082,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1934.549609,-775.834112,NaN
65,Expense,64880.0,Travel Costs,-774.375741,-1560.009858,-3000.90442,-10289.613277,-19127.216449,-2636.555436,-1393.547808,...,-21829.790043,-1870.905468,-1492.67986,-1297.628145,-3329.288491,-424.393831,-5131.956915,-2946.18306,-1818.709274,-160.092186
73,Expense,498.0,Unrealised Currency Gains,NaN,-640.144117,NaN,NaN,3931.590823,NaN,-3740.60279,...,4487.103622,NaN,-4006.696014,-4.604661,780.92836,2235.080246,-548.022593,-2111.591851,NaN,-65.69322
47,Expense,64658.0,Water,-45.136126,-1267.757428,-103.276115,-179.702733,-267.620102,-264.827834,-1080.849903,...,-305.433394,-187.922407,-1157.737735,-305.933012,-94.04407,-395.497762,-1177.016798,-571.601547,-106.007311,-130.100497

In [33]:
# # new_expense_forecast
# columns_to_sum_1 = new_expense_forecast.columns[3:]
# column_sums_1 = new_expense_forecast[columns_to_sum_1].sum()
# print(column_sums_1)

august_2024       -502896.584134
september_2024   -1811563.997105
october_2024     -1972630.406472
november_2024     -1732121.97941
december_2024    -2051333.152774
january_2025     -2544634.368276
february_2025    -1557343.376821
march_2025       -2071479.715478
april_2025       -2218259.654074
may_2025          -1712860.33333
june_2025        -2347603.605094
july_2025        -2218951.937178
august_2025      -1343137.957723
september_2025   -1887569.747031
october_2025     -1485728.210174
november_2025    -1620617.428387
december_2025     -2498515.66049
january_2026      -1868062.36367
february_2026    -1411987.829561
march_2026       -1941501.371255
april_2026       -2084056.139912
may_2026         -1600683.808659
june_2026        -2808729.331983
july_2026        -1592052.322318
august_2026       -1263056.02193
september_2026   -1713091.022095
october_2026     -1378973.962634
november_2026    -1509606.188245
december_2026    -2341175.578518
january_2027     -1805678.077925
february_2027     -1668127.26472
march_2027       -1817333.209334
april_2027       -1555201.860251
may_2027          -1488118.32709
june_2027        -2618017.703343
july_2027        -1492639.192348
august_2027      -1181109.676419
september_2027    -185907.312828
dtype: object

In [30]:
def prepare_forecast_rows(forecast_df):
    
    rows_to_add = []
    
    for i, row in forecast_df.iterrows():
        for date_col in forecast_df.columns[3:]:
            
            # Change the date to standardized format
            date_obj = datetime.strptime(date_col, '%B_%Y')
            formatted_date = date_obj.strftime('%m/01/%Y')
            
            # Row dictionary
            new_row = {
                'Date': formatted_date,  
                'Account Code': row['account_code'],  
                'Account Type': row['account_type'], 
                'Account': row['account'],  
                'Amount': row[date_col],  
                # Other columns in gl_df will be left empty, status will be set to 'Budget'
                'Source': '', 'Description': '', 'Invoice Number': '', 'Reference': '',
                'Journal ID': '', 'Debit': '', 'Credit': '', 'Gross': '', 'GST': '', 'Net': '',
                'GST Rate': '', 'GST Rate Name': '', 'Cost Centre': '', 'Unique ID': '', 
                'Status': 'CP Forecast'
            }
            
            rows_to_add.append(new_row)
    
    return pd.DataFrame(rows_to_add)

new_sales_rows = prepare_forecast_rows(new_sales_forecast)
new_direct_costs_rows = prepare_forecast_rows(new_direct_costs_forecast)
new_other_income_rows = prepare_forecast_rows(new_other_income_forecast)
new_expense_rows = prepare_forecast_rows(new_expense_forecast)

# Concatenate all new rows to the existing gl_df
gl_df = pd.concat([gl_df, new_sales_rows, new_direct_costs_rows, new_other_income_rows, new_expense_rows], ignore_index=True)

In [31]:
gl_df.tail(10)

,Date,Account Code,Account Type,Account,Source,Description,Invoice Number,Reference,Journal ID,Debit,Credit,Gross,GST,Net,GST Rate,GST Rate Name,Cost Centre,Amount,Unique ID,Status
385736,11/01/2026,64658.0,Expense,Water,,,,,,,,,,,,,,-202.692338,,CP Forecast
385737,12/01/2026,64658.0,Expense,Water,,,,,,,,,,,,,,-231.756469,,CP Forecast
385738,01/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-183.782017,,CP Forecast
385739,02/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-1117.745115,,CP Forecast
385740,03/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-304.307504,,CP Forecast
385741,04/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-94.213181,,CP Forecast
385742,05/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-499.192831,,CP Forecast
385743,06/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-832.839808,,CP Forecast
385744,07/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-493.711325,,CP Forecast
385745,08/01/2027,64658.0,Expense,Water,,,,,,,,,,,,,,-15.743190,,CP Forecast

In [32]:
gl_df.to_csv('gl_df_export.csv', index=False)

#### EBITDA Forecast

In [23]:
# # This part will be deleted. Just to store hard-coded EBITDA number for now
# # List of EBITDA values
# ebitda_values = [445277, 90700, 10865, 156252, 401139, 368620, -184037, -47912, -151353, 
#     -449466, -235587, -98650, 114116, 1264647]

In [24]:
# ebitda_df = pd.DataFrame({
#     'Date': column_sums.index,        
#     'Revenue': column_sums.values,    
#     'EBITDA': ebitda_values           
# })

In [25]:
# ebitda_df['EBITDA_percentage'] = ebitda_df['EBITDA']/ebitda_df['Revenue']
# ebitda_df

In [26]:
# # Function to identify months, average them, and store the output in separate datasets
# def process_ebitda_df(df):

#     averaged_df = pd.DataFrame(columns=['Month', 'Average_EBITDA_Percentage'])

#     for month in ['january', 'february', 'march', 'april', 'may', 'june', 
#                   'july', 'august', 'september', 'october', 'november', 'december']:
#         month_data = df[df['Date'].str.startswith(month)]
        
#         if not month_data.empty:
#             avg_ebitda_percent = month_data['EBITDA_percentage'].mean()

#             averaged_df = averaged_df.append({
#                 'Month': month,
#                 'Average_EBITDA_Percentage': avg_ebitda_percent
#             }, ignore_index=True)

#     return averaged_df

# ebitda_percent_df = process_ebitda_df(ebitda_df)

In [27]:
# ebitda_percent_df

In [28]:
# ebitda_forecast_df = df_revenue_forecast

# ebitda_forecast_df['Month_only'] = ebitda_forecast_df['Month'].str.extract(r'([a-zA-Z]+)')

# ebitda_forecast_df['EBITDA Forecast'] = None

# # Calculate the 'EBITDA Forecast' for each row in ebitda_forecast_df
# for i, row in ebitda_forecast_df.iterrows():
#     matching_row = ebitda_percent_df[ebitda_percent_df['Month'] == row['Month_only']]
    
#     if not matching_row.empty:
#         ebitda_forecast_df.at[i, 'EBITDA Forecast'] = row['Revenue Forecast'] * matching_row['Average_EBITDA_Percentage'].values[0]

# ebitda_forecast_df.drop(columns=['Month_only'], inplace=True)

# ebitda_forecast_df

In [29]:
#gl_df.to_csv('gl_df.csv', index=False)